
server:
  port:  8092

spring:
  config:
    import: optional:configserver:http://localhost:8095
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/microratingservice?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  application:
    name: RATING-SERVICE 
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

   
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

    
    
    
#
#spring.datasource.url=
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=
#spring.jpa.properties.hibernate.dialect=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.hibernate.use-new-id-generator-mappings= false
#    name: 